name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3 # Replaces chmod and direct gradlew call
      with:
        # gradle-version: wrapper # This would ideally use the wrapper, but it's missing.
                                 # The action can also use a specific Gradle version or discover it.
        # cache-read-only: false # Adjust caching as needed
        # build-root-directory: '.' # Default is repository root

    - name: Build with Gradle
      run: gradle assembleRelease # Use 'gradle' directly after setup-gradle

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release-unsigned.apk
